
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module projekat(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,
	
	
	//////////// SEG7 //////////
	output 		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		   [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,
   input 		     [35:0]		GPIO_1

);

wire [2:0] tstanje;
wire [2:0] sstanje;
wire [4:0] sticiDo; 
wire vrata;

promenaStanja x (sstanje, tstanje, sticiDo, CLOCK_50, KEY, GPIO_1[0], SW[1:0], vrata);
prikaz y (tstanje, LEDR, HEX0, HEX1, HEX2, HEX3,  HEX4, HEX5, vrata);
	

//reg [2:0] stanje;


//reg [9:0] vreme;//prebaciti iz ulaza/izlaza
//reg [25:0] br;
//	
//always @ (posedge CLOCK_50) begin
//	if(br == 26'd50000000) begin
//		vreme = vreme + 10'd1;
//		br = 26'd0;
//	end
//	else begin
//		br = br + 26'd1;
//	end
//	if(KEY[0] == 0) vreme = 10'd0;
//	
//end

//always @ (GPIO_1[0]) begin
	//HEX0[1] = GPIO_1[0];
	//HEX0[0] = SW[0];
//end

//=======================================================
//  REG/WIRE declarations
//=======================================================


//=======================================================
//  Structural coding
//=======================================================

	//assign LEDR = 10'hAA;

endmodule
